#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 23 18:31:18 2017

@author: dawit
"""

import numpy as np
from sklearn.utils import shuffle
import pickle
from sklearn.cross_validation import train_test_split
from keras.utils import np_utils

nb_classes = 10
img_rows, img_cols = 96,96

with open('afile','rb') as f:
     images= pickle.load(f)

with open('labels','rb') as f:
     labels= pickle.load(f)

immatrix = np.array([np.array(im2).flatten()
              for im2 in images],'f')
data,Label = shuffle(immatrix,labels, random_state=2)
train_data = [data,Label]

(X, y) = (train_data[0],train_data[1])
#split X and y into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols,3)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols,3)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')


X1_train = np.asarray(X_train).reshape((-1, 32, 32, 3))
X1_test = np.asarray(X_test).reshape((-1, 32, 32, 3))
X2_train = np.asarray(X_train).reshape((-1, 32, 32, 3))
X2_test = np.asarray(X_test).reshape((-1, 32, 32, 3))

X_train /= 255
X_test /= 255

# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(np.asarray(y_train),10)
Y_test = np_utils.to_categorical(np.asarray(y_test),10)